language: python
python: 3.6

script:
- pip install hoedown pyrss2gen
- cp -r ./document ./silverblog/document
- cp -r ./config ./silverblog/config
- cp -r templates ./silverblog/templates
- cd silverblog
- git clone https://@github.com/${github_repo} static_page
- ./manage.py build-page